/**
 * Metadata summary text generation
 */

export function buildMetadataSummary(data: {
  script: any;
  version: any;
}): string {
  const lines = [
    "Record generated by DraftLock",
    "This document contains timestamps and metadata associated with a protected version.",
    "",
    "METADATA SUMMARY",
    "",
    "Script Information:",
    `  Title: ${data.script.title || "Untitled"}`,
    `  Script ID: ${data.script.id}`,
    `  Work Type: ${data.script.work_type || "—"}`,
    `  Created: ${data.script.created_at ? new Date(data.script.created_at).toISOString() : "—"}`,
    "",
    "Version Information:",
    `  Version ID: ${data.version.id}`,
    `  Original Filename: ${data.version.original_filename || "—"}`,
    `  File Size: ${data.version.byte_size ? `${data.version.byte_size} bytes` : "—"}`,
    `  MIME Type: ${data.version.mime_type || "—"}`,
  ];

  if (data.version.page_count !== null) {
    lines.push(`  Page Count: ${data.version.page_count} ${data.version.page_count === 1 ? "page" : "pages"}`);
  }

  lines.push(
    `  SHA-256 Hash: ${data.version.sha256 || "—"}`,
    `  Committed At: ${data.version.committed_at ? new Date(data.version.committed_at).toISOString() : "—"}`,
  );

  if (data.version.snapshot_path) {
    lines.push(
      `  Script Snapshot: Available`,
      `    Script snapshot — A static PDF snapshot of the uploaded version at the time of protection.`
    );
  }

  lines.push(
    "",
    "Notes:",
    `  ${data.script.notes || "No notes provided."}`,
    "",
    "DraftLock is not a law firm and does not provide legal advice."
  );

  return lines.join("\n");
}
