export function buildReceiptText(input: {
  title: string;
  draftId: string;
  versionId: string;
  filename: string;
  byteSize: number;
  sha256: string;
  timestampUtc: string;
  txHash?: string | null;
  blockNumber?: number | null;
  chainRegisteredAt?: string | null;
}) {
  const lines = [
    "Record generated by ProofMark",
    "This document contains timestamps and metadata associated with a protected version.",
    "",
    "PROOFMARK AUTHORSHIP RECEIPT",
    "",
    `Title of work: ${input.title}`,
    `Draft ID: ${input.draftId}`,
    `Version ID: ${input.versionId}`,
    `Original filename: ${input.filename}`,
    `File size (bytes): ${input.byteSize}`,
    `SHA-256 hash: ${input.sha256}`,
    `Timestamp (UTC): ${input.timestampUtc}`,
  ];

  if (input.txHash) {
    const explorerBase = process.env.AVALANCHE_CHAIN_ID === '43114'
      ? 'https://snowtrace.io'
      : 'https://testnet.snowtrace.io';

    lines.push(
      "",
      "ON-CHAIN VERIFICATION (Avalanche C-Chain)",
      `Transaction hash: ${input.txHash}`,
      `Block number: ${input.blockNumber ?? "N/A"}`,
      `Registered on-chain: ${input.chainRegisteredAt ?? "N/A"}`,
      `Explorer: ${explorerBase}/tx/${input.txHash}`,
      `Verify: ${process.env.NEXT_PUBLIC_APP_URL || "https://proofmark.xyz"}/verify?hash=${input.sha256}`,
    );
  }

  lines.push(
    "",
    "This receipt records the file fingerprint and timestamp associated with this draft version.",
    "This document does not constitute legal advice or a government registration."
  );

  return lines.join("\n");
}

export function buildFilingWorksheet(input: {
  title: string;
  authorship: string;
  publicationStatus: string;
  workForHire: string;
  preexistingMaterial: string;
}) {
  return [
    "Record generated by ProofMark",
    "This document contains timestamps and metadata associated with a protected version.",
    "",
    "GUIDED FILING WORKSHEET (UNITED STATES)",
    "",
    "This worksheet summarizes information commonly requested during copyright registration.",
    "It is provided for convenience and does not replace official instructions.",
    "",
    `Title of work: ${input.title}`,
    `Authorship: ${input.authorship}`,
    `Publication status: ${input.publicationStatus}`,
    `Work made for hire: ${input.workForHire}`,
    `Preexisting material: ${input.preexistingMaterial}`,
    "",
    "Notes:",
    "- Registration is effective when a complete submission is received.",
    "- Retain your deposit copy and confirmation receipts."
  ].join("\n");
}

export function buildReadme() {
  return [
    "Record generated by ProofMark",
    "This document contains timestamps and metadata associated with a protected version.",
    "",
    "PROOFMARK EVIDENCE PACK",
    "",
    "This packet contains timestamped records and metadata provided by the user.",
    "It is intended to help document authorship and draft history.",
    "",
    "ProofMark is not a law firm and does not provide legal advice."
  ].join("\n");
}
