export function buildReceiptText(input: {
  title: string;
  draftId: string;
  versionId: string;
  filename: string;
  byteSize: number;
  sha256: string;
  timestampUtc: string;
}) {
  return [
    "Record generated by DraftLock",
    "This document contains timestamps and metadata associated with a protected version.",
    "",
    "DRAFTLOCK AUTHORSHIP RECEIPT",
    "",
    `Title of work: ${input.title}`,
    `Draft ID: ${input.draftId}`,
    `Version ID: ${input.versionId}`,
    `Original filename: ${input.filename}`,
    `File size (bytes): ${input.byteSize}`,
    `SHA-256 hash: ${input.sha256}`,
    `Timestamp (UTC): ${input.timestampUtc}`,
    "",
    "This receipt records the file fingerprint and timestamp associated with this draft version.",
    "This document does not constitute legal advice or a government registration."
  ].join("\n");
}

export function buildFilingWorksheet(input: {
  title: string;
  authorship: string;
  publicationStatus: string;
  workForHire: string;
  preexistingMaterial: string;
}) {
  return [
    "Record generated by DraftLock",
    "This document contains timestamps and metadata associated with a protected version.",
    "",
    "GUIDED FILING WORKSHEET (UNITED STATES)",
    "",
    "This worksheet summarizes information commonly requested during copyright registration.",
    "It is provided for convenience and does not replace official instructions.",
    "",
    `Title of work: ${input.title}`,
    `Authorship: ${input.authorship}`,
    `Publication status: ${input.publicationStatus}`,
    `Work made for hire: ${input.workForHire}`,
    `Preexisting material: ${input.preexistingMaterial}`,
    "",
    "Notes:",
    "- Registration is effective when a complete submission is received.",
    "- Retain your deposit copy and confirmation receipts."
  ].join("\n");
}

export function buildReadme() {
  return [
    "Record generated by DraftLock",
    "This document contains timestamps and metadata associated with a protected version.",
    "",
    "DRAFTLOCK EVIDENCE PACK",
    "",
    "This packet contains timestamped records and metadata provided by the user.",
    "It is intended to help document authorship and draft history.",
    "",
    "DraftLock is not a law firm and does not provide legal advice."
  ].join("\n");
}
