/**
 * Registration Worksheet generation
 * A worksheet to help with copyright registration
 */

export function buildRegistrationWorksheet(data: {
  script: any;
  version: any;
}): string {
  const lines = [
    "Registration Worksheet",
    "Generated by ProofMark",
    "",
    "This worksheet organizes information that may be useful when registering copyright.",
    "ProofMark is not a law firm and does not provide legal advice.",
    "",
    "WORK INFORMATION",
    "",
    `Title of work: ${data.script.title || "Untitled"}`,
    `Work type: ${data.script.work_type || "N/A"}`,
    `Script ID: ${data.script.id}`,
    `Version ID: ${data.version.id}`,
    "",
    "FILE INFORMATION",
    "",
    `Original filename: ${data.version.original_filename || "N/A"}`,
    `File size: ${data.version.byte_size ? `${data.version.byte_size} bytes` : "N/A"}`,
    `MIME type: ${data.version.mime_type || "N/A"}`,
  ];

  if (data.version.page_count !== null) {
    lines.push(`Page count: ${data.version.page_count} ${data.version.page_count === 1 ? "page" : "pages"}`);
  }

  lines.push(
    "",
    "FINGERPRINT",
    "",
    `Algorithm: SHA-256`,
    `Hash: ${data.version.sha256 || "N/A"}`,
    "",
    "TIMESTAMP",
    "",
    `Committed at (UTC): ${data.version.committed_at ? new Date(data.version.committed_at).toISOString() : "N/A"}`,
    "",
    "AUTHORSHIP",
    "",
    `Authors count: ${data.script.authors_count || "N/A"}`,
    `Publication status: ${data.script.publication_status || "N/A"}`,
    `Work made for hire: ${data.script.work_made_for_hire || "N/A"}`,
    `Preexisting material: ${data.script.preexisting_material || "N/A"}`,
    "",
    "NOTES",
    "",
    data.script.notes || "No notes provided.",
    "",
    "DISCLAIMER",
    "",
    "This worksheet is provided for organizational purposes only.",
    "It does not constitute legal advice or a government registration.",
    "For official registration, follow the instructions provided by the",
    "U.S. Copyright Office or consult with a qualified attorney.",
    "",
    "ProofMark is not a law firm and does not provide legal advice."
  );

  return lines.join("\n");
}
