/**
 * Registration Worksheet PDF generation
 * Generates a plain-English registration worksheet PDF for copyright filing
 */

import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

export async function generateRegistrationWorksheetPDF(data: {
  script: any;
  version: any;
}): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]); // US Letter size
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const margin = 72; // 1 inch margins
  let y = page.getHeight() - margin;
  const lineHeight = 14;
  const sectionSpacing = 20;
  const smallLineHeight = 10;

  // Helper function to draw wrapped text
  const drawWrappedText = (text: string, maxWidth: number, size: number, useFont: any, color: any) => {
    const words = text.split(" ");
    let line = "";
    let lines: string[] = [];
    
    for (const word of words) {
      const testLine = line + (line ? " " : "") + word;
      const testWidth = useFont.widthOfTextAtSize(testLine, size);
      if (testWidth > maxWidth && line) {
        lines.push(line);
        line = word;
      } else {
        line = testLine;
      }
    }
    if (line) lines.push(line);
    
    return lines;
  };

  // Header
  page.drawText("Registration Worksheet", {
    x: margin,
    y,
    size: 18,
    font: boldFont,
    color: rgb(0, 0, 0),
  });
  y -= 20;

  page.drawText("Generated by DraftLock", {
    x: margin,
    y,
    size: 10,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });
  y -= sectionSpacing * 1.5;

  // Introduction
  const introText = "This worksheet summarizes information you provided that is commonly requested during copyright registration. Each field below includes a brief explanation of how it is typically used during filing.";
  const introLines = drawWrappedText(introText, page.getWidth() - margin * 2, 10, font, rgb(0, 0, 0));
  for (const line of introLines) {
    page.drawText(line, {
      x: margin,
      y,
      size: 10,
      font,
      color: rgb(0, 0, 0),
    });
    y -= lineHeight;
  }
  y -= sectionSpacing;

  // Title
  page.drawText("Title of work", {
    x: margin,
    y,
    size: 12,
    font: boldFont,
    color: rgb(0, 0, 0),
  });
  y -= lineHeight + 2;

  page.drawText(data.script.title || "Untitled", {
    x: margin,
    y,
    size: 11,
    font,
    color: rgb(0, 0, 0),
  });
  y -= lineHeight + 4;

  const titleHelper = "Used to identify your work in the registration application. Keep this consistent across versions and filings.";
  const titleHelperLines = drawWrappedText(titleHelper, page.getWidth() - margin * 2, 9, font, rgb(0.4, 0.4, 0.4));
  for (const line of titleHelperLines) {
    page.drawText(line, {
      x: margin,
      y,
      size: 9,
      font,
      color: rgb(0.4, 0.4, 0.4),
    });
    y -= smallLineHeight;
  }
  y -= sectionSpacing - smallLineHeight;

  // Work Type
  page.drawText("Work type", {
    x: margin,
    y,
    size: 12,
    font: boldFont,
    color: rgb(0, 0, 0),
  });
  y -= lineHeight + 2;

  page.drawText(data.script.work_type || "—", {
    x: margin,
    y,
    size: 11,
    font,
    color: rgb(0, 0, 0),
  });
  y -= lineHeight + 4;

  const workTypeHelper = "Describes the category of your work (e.g., Screenplay, Manuscript, Treatment). This helps classify your work in the registration system.";
  const workTypeHelperLines = drawWrappedText(workTypeHelper, page.getWidth() - margin * 2, 9, font, rgb(0.4, 0.4, 0.4));
  for (const line of workTypeHelperLines) {
    page.drawText(line, {
      x: margin,
      y,
      size: 9,
      font,
      color: rgb(0.4, 0.4, 0.4),
    });
    y -= smallLineHeight;
  }
  y -= sectionSpacing - smallLineHeight;

  // Authors count
  page.drawText("Authors count", {
    x: margin,
    y,
    size: 12,
    font: boldFont,
    color: rgb(0, 0, 0),
  });
  y -= lineHeight + 2;

  page.drawText(String(data.script.authors_count || "—"), {
    x: margin,
    y,
    size: 11,
    font,
    color: rgb(0, 0, 0),
  });
  y -= lineHeight + 4;

  const authorsHelper = "The number of authors who contributed to this work. Used to determine ownership shares and who must be listed in the registration.";
  const authorsHelperLines = drawWrappedText(authorsHelper, page.getWidth() - margin * 2, 9, font, rgb(0.4, 0.4, 0.4));
  for (const line of authorsHelperLines) {
    page.drawText(line, {
      x: margin,
      y,
      size: 9,
      font,
      color: rgb(0.4, 0.4, 0.4),
    });
    y -= smallLineHeight;
  }
  y -= sectionSpacing - smallLineHeight;

  // Publication status
  page.drawText("Publication status", {
    x: margin,
    y,
    size: 12,
    font: boldFont,
    color: rgb(0, 0, 0),
  });
  y -= lineHeight + 2;

  page.drawText(data.script.publication_status || "—", {
    x: margin,
    y,
    size: 11,
    font,
    color: rgb(0, 0, 0),
  });
  y -= lineHeight + 4;

  const pubHelper = "Indicates whether your work has been published. Published works have different registration requirements and deadlines than unpublished works.";
  const pubHelperLines = drawWrappedText(pubHelper, page.getWidth() - margin * 2, 9, font, rgb(0.4, 0.4, 0.4));
  for (const line of pubHelperLines) {
    page.drawText(line, {
      x: margin,
      y,
      size: 9,
      font,
      color: rgb(0.4, 0.4, 0.4),
    });
    y -= smallLineHeight;
  }
  y -= sectionSpacing - smallLineHeight;

  // Work made for hire
  page.drawText("Work made for hire", {
    x: margin,
    y,
    size: 12,
    font: boldFont,
    color: rgb(0, 0, 0),
  });
  y -= lineHeight + 2;

  page.drawText(data.script.work_made_for_hire || "—", {
    x: margin,
    y,
    size: 11,
    font,
    color: rgb(0, 0, 0),
  });
  y -= lineHeight + 4;

  const hireHelper = "Indicates if this work was created as part of employment or under a specific agreement. This affects who holds the copyright.";
  const hireHelperLines = drawWrappedText(hireHelper, page.getWidth() - margin * 2, 9, font, rgb(0.4, 0.4, 0.4));
  for (const line of hireHelperLines) {
    page.drawText(line, {
      x: margin,
      y,
      size: 9,
      font,
      color: rgb(0.4, 0.4, 0.4),
    });
    y -= smallLineHeight;
  }
  y -= sectionSpacing - smallLineHeight;

  // Preexisting material
  page.drawText("Preexisting material", {
    x: margin,
    y,
    size: 12,
    font: boldFont,
    color: rgb(0, 0, 0),
  });
  y -= lineHeight + 2;

  page.drawText(data.script.preexisting_material || "—", {
    x: margin,
    y,
    size: 11,
    font,
    color: rgb(0, 0, 0),
  });
  y -= lineHeight + 4;

  const preexistingHelper = "Describes any material from other sources incorporated into your work. This must be disclosed in registration to clarify what is new versus what already existed.";
  const preexistingHelperLines = drawWrappedText(preexistingHelper, page.getWidth() - margin * 2, 9, font, rgb(0.4, 0.4, 0.4));
  for (const line of preexistingHelperLines) {
    page.drawText(line, {
      x: margin,
      y,
      size: 9,
      font,
      color: rgb(0.4, 0.4, 0.4),
    });
    y -= smallLineHeight;
  }
  y -= sectionSpacing * 1.5;

  // Filing Checklist
  page.drawText("Filing Checklist", {
    x: margin,
    y,
    size: 14,
    font: boldFont,
    color: rgb(0, 0, 0),
  });
  y -= lineHeight + 6;

  const checklistItems = [
    "Complete the official registration application form",
    "Prepare a deposit copy of your work (as required by the Copyright Office)",
    "Gather all author information and contact details",
    "Determine the correct registration class for your work type",
    "Review publication dates and first publication information if applicable",
    "Verify work made for hire status and agreements if applicable",
    "Identify and document any preexisting material if applicable",
    "Submit the application with required fees to the U.S. Copyright Office",
    "Retain copies of all submitted materials and confirmation receipts"
  ];

  for (const item of checklistItems) {
    page.drawText("□", {
      x: margin,
      y,
      size: 11,
      font,
      color: rgb(0, 0, 0),
    });
    
    const itemLines = drawWrappedText(item, page.getWidth() - margin * 2 - 20, 10, font, rgb(0, 0, 0));
    let itemY = y;
    for (const line of itemLines) {
      page.drawText(line, {
        x: margin + 20,
        y: itemY,
        size: 10,
        font,
        color: rgb(0, 0, 0),
      });
      itemY -= lineHeight;
    }
    y = itemY - 4;
  }

  y -= sectionSpacing;

  // Disclaimer
  page.drawText("DraftLock does not submit filings or provide legal advice.", {
    x: margin,
    y,
    size: 10,
    font: boldFont,
    color: rgb(0.4, 0.4, 0.4),
  });
  y -= lineHeight + 4;

  const disclaimerText = "This worksheet is provided for organizational purposes only. It does not constitute legal advice, a government registration, or a guarantee of registration. For official registration, follow the instructions provided by the U.S. Copyright Office or consult with a qualified attorney.";
  const disclaimerLines = drawWrappedText(disclaimerText, page.getWidth() - margin * 2, 9, font, rgb(0.4, 0.4, 0.4));
  for (const line of disclaimerLines) {
    page.drawText(line, {
      x: margin,
      y,
      size: 9,
      font,
      color: rgb(0.4, 0.4, 0.4),
    });
    y -= smallLineHeight;
  }

  // Generate PDF bytes and return as Buffer
  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
}
