/**
 * PDF snapshot generation utility
 * Extracted from snapshot route for reuse in packet generation
 */

import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

export async function generateSnapshotPDF(data: {
  title: string;
  scriptId: string;
  versionId: string;
  filename: string;
  byteSize: number | null;
  pageCount: number | null;
  sha256: string;
  committedAt: string;
}): Promise<Buffer> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([612, 792]); // US Letter size
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const margin = 72; // 1 inch margins
  let y = page.getHeight() - margin;
  const lineHeight = 14;
  const sectionSpacing = 20;

  // Header
  page.drawText("Record generated by ProofMark", {
    x: margin,
    y,
    size: 10,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });
  y -= 12;

  page.drawText("This document contains timestamps and metadata associated with a protected version.", {
    x: margin,
    y,
    size: 9,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });
  y -= sectionSpacing;

  // Title
  page.drawText("PROOFMARK EVIDENCE RECORD", {
    x: margin,
    y,
    size: 16,
    font: boldFont,
    color: rgb(0, 0, 0),
  });
  y -= sectionSpacing;

  // Metadata section
  const metadata: Array<[string, string]> = [
    ["Title of work", data.title || "Untitled"],
    ["Draft ID", data.scriptId],
    ["Version ID", data.versionId],
    ["Original filename", data.filename || "N/A"],
  ];

  if (data.pageCount !== null) {
    metadata.push(["Page count", `${data.pageCount} ${data.pageCount === 1 ? "page" : "pages"}`]);
  }

  if (data.byteSize !== null) {
    metadata.push(["File size", `${data.byteSize} bytes`]);
  }

  metadata.push(
    ["SHA-256 hash", data.sha256],
    ["Timestamp (UTC)", data.committedAt]
  );

  for (const [label, value] of metadata) {
    page.drawText(`${label}:`, {
      x: margin,
      y,
      size: 10,
      font: boldFont,
      color: rgb(0, 0, 0),
    });

    // Wrap long values (especially hash)
    const valueStr = String(value);
    const maxWidth = page.getWidth() - margin * 2 - 120;
    
    if (valueStr.length > 50) {
      // For long values like hashes, break into multiple lines
      const chunks = valueStr.match(/.{1,50}/g) || [valueStr];
      let currentY = y;
      for (const chunk of chunks) {
        page.drawText(chunk, {
          x: margin + 120,
          y: currentY,
          size: 9,
          font,
          color: rgb(0, 0, 0),
        });
        currentY -= lineHeight;
      }
      y = currentY - 4;
    } else {
      page.drawText(valueStr, {
        x: margin + 120,
        y,
        size: 10,
        font,
        color: rgb(0, 0, 0),
      });
      y -= lineHeight;
    }
  }

  y -= sectionSpacing;

  // Footer
  page.drawText("This receipt records the file fingerprint and timestamp associated with this draft version.", {
    x: margin,
    y,
    size: 9,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });
  y -= 12;

  page.drawText("ProofMark is not a law firm and does not provide legal advice.", {
    x: margin,
    y,
    size: 9,
    font,
    color: rgb(0.4, 0.4, 0.4),
  });

  // Generate PDF bytes and return as Buffer
  const pdfBytes = await pdfDoc.save();
  return Buffer.from(pdfBytes);
}
