import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer",
  description: "ProofMark disclaimer. ProofMark provides proof-of-origin, not legal advice or copyright registration.",
};

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen">
      <section className="max-w-4xl mx-auto px-6 pt-32 pb-24">
        <h1 className="text-3xl font-semibold text-[var(--text)]">Disclaimer</h1>

        <div className="mt-8 space-y-6 text-sm text-[var(--muted)] leading-relaxed">
          <p>
            ProofMark provides tools for documenting creative work and version history.
          </p>

          <p>
            ProofMark is not a law firm and does not provide legal advice. Information
            generated by the service is not a substitute for professional legal counsel
            or formal copyright registration.
          </p>

          <p>
            Use of ProofMark does not guarantee legal outcomes or protection. You are
            responsible for determining how records are used in your workflow.
          </p>
        </div>
      </section>
    </main>
  );
}
